"""init db

Revision ID: 0174802cc687
Revises: 
Create Date: 2024-11-17 12:05:15.028526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0174802cc687'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('ticket_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('seat_number', sa.String(length=10), nullable=True),
    sa.Column('status', sa.Enum('available', 'reserved', 'sold', name='ticketstatus'), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('purchase_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('ticket_id'),
    sa.UniqueConstraint('event_id', 'seat_number', name='uq_event_seat'),
    schema='event_management'
    )
    op.create_index('ix_status_purchase_time', 'tickets', ['status', 'purchase_time'], unique=False, schema='event_management')
    op.drop_index('idx_customer_birthday', table_name='customer')
    op.drop_index('idx_customer_name', table_name='customer', postgresql_using='hash')
    op.drop_table('customer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='customer_pkey')
    )
    op.create_index('idx_customer_name', 'customer', ['name'], unique=False, postgresql_using='hash')
    op.create_index('idx_customer_birthday', 'customer', ['birthday'], unique=False)
    op.drop_index('ix_status_purchase_time', table_name='tickets', schema='event_management')
    op.drop_table('tickets', schema='event_management')
    # ### end Alembic commands ###
